name: PyLint
on:
  push:
    paths:
    - "**.py"
  workflow_dispatch:
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install libraries
        run: pip install autopep8 autoflake isort black
      - name: Check for showstoppers
        run: |
          find . -name "*.py" | xargs autopep8 --verbose --in-place --aggressive
      - name: Remove unused imports
        run: |
          find . -name "*.py" | xargs autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports
      - name: Lint with black
        run: |
          black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Pylint: Auto Fixes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: DONATE-ARMY-BOTS
          commit_user_email: 167422483+DONATE-ARMY-BOTS@users.noreply.github.com
          commit_author: DONATE-ARMY-BOTS <167422483+DONATE-ARMY-BOTS@users.noreply.github.com>
